apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.flask.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-flask-app-service
            port:
              number: {{ .Values.flask.svcPort }}
#  tls:
#  - hosts:
#      - {{ .Values.flask.ingress.host }}
#    secretName: {{ .Values.flasktlsSecretName }}

  - host: {{ .Values.phpMyAdmin.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-phpmyadmin-service
            port:
              number: {{ .Values.phpMyAdmin.svcPort }}
  tls:
  - hosts:
      - {{ .Values.phpMyAdmin.ingress.host }}
    secretName: {{ .Values.phptlsSecretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.flasktlsSecretName }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "flask-app.local.crt" | b64enc | quote }}
  tls.key: {{ .Files.Get "flask-app.local.key" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.phptlsSecretName }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "phpmyadmin.local.crt" | b64enc | quote }}
  tls.key: {{ .Files.Get "phpmyadmin.local.key" | b64enc | quote }}